apiVersion: v1
kind: Pod
metadata:
  name: accomplay
  labels:
    name: accomplay
spec:
  containers:
#    - image: mongo:latest
#      name: mongo
#      ports:
#        - containerPort: 27017
#          name: mongo
    - image: ksonney/phoenixlounge:latest
      name: accomplay
      env:
        - name: NODE_DB_URI
          value: mongodb://mongosvc/habitrpg
      ports: 
        - containerPort: 3000
          hostPort: 3000
          name: accomplay
